travis:
  secure:
    BINSTAR_TOKEN: UrNsKdVm3Yupx1jOWMtARTZk3iRm/sNfcnlSwCwzrl4p4OdBvr6qBMbOk6E6Jy3rcMkbjYYrrG2DkhQ3eYV6ievS7KxjQiMzRsychB4Jg8VAb+3e7KD6Vf3KsRwHKKnhGECQsmHAzmMCayiUIrBdCG80OKu0LivFZ3ymW5zzSLu79S0nJTp7kSdSJH+ar5eA181xB/eSrBWDtDTws5JhI4LneW0+0+kRC2QejFOiCkHKGdeKPKYle7Noe7txmrWa4v/oTBW9NpQzOhysZT25Nkk+cC6eGK9t3MyLlHMev1ShhSLpry1XNwAj4BkEvTW3Rc8grVX4QuO3RK8iwpDiIGsu1dmTFl+izKt9ibPU5DfB0jic9jWJJAuNAR7Bvee9kQ/0ClHFqWkeCJt/XujD1y/yh3Hxll0iZ9fTmQzAdVDgkITCG37TBg0C+NvD/2gIpjZyf9OIhP1UVwDR/R8j6bvcgjLrUTLPZSbL0vTlYVNA31Yqwj8Iq2kb5+ziam8DM8IH+lyWbMVAnvfmS4zq9bcGzTOkJK/axrdaobyRx8gokC8O7UWGlnw8vaROVoSMyIhRyVlRZhWGBAjFz1MHjhLRC9ohCIDtw0xge6i2lC883tPN1fhV1OiMirhCYzd39qnGK5n6wVIJ9bem0pSeTPLsvPzV4qFSKFGPo4IC9g4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
