travis:
  secure:
    BINSTAR_TOKEN: GUylkda1Mh/fC2ejQX/u4fDY1R6ZjmCTJgPH4K/Vwq/egZ9jWh7vqYdQm3UHwGKq8zHRX/NyNcCWJPqUAj9Y53/w0Nnuh2Cruf+fAB8fVoersydzEg7gvb4NCOwE34lEETLvfFnL0lG0rEUx6NCty6CAIgdCYfuvGCQIB4YE51qQ28RpUgX5icDCERYeQi571DfgfkPmihhnxWNDkmpMKQjOFROaZX1q3tPrIjt0kK8h1yItIgAcI4uZiHH3Xj9Ueeamsh+/Npq/8KXuHWqbPyzrnp8QqQrcgGO7+xulR5CbHL5A5a/94Sj72fkyGTDrpVY6twQ6YwlMs2nwJ6oFP69z/F5MmiOE3AozpQjOzc85M5xnP6+9r/eFj7uKGXDXK6O1Z+bGNFYx6FjNhVgjrxXo7aV+c/I9w1/QeydTWSfBajSzRyhvQI9/dxRHtVZd0Edz3pwxZ7wE/c/11vhnImp9jnnFCYZ1Z4Jp6uSEkt/7fUe+vFtcwgHJq5sowchc1rBehiyaWyjEdKN43jfK9CkT6GRBgSO9h4jf80XgDxXhMfCKNvAdK02DNel5bfInScNxZPhr0ewuID5t7BSsOBPh1+ejAABXXF+YorC7TltnRgvn6t8zTnJm6NMvwNwoLe5mt1rxMUFWl9Iz4H7w/ucrNw7AsP/l9mgLRAQB2yU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
